Repository 2024-9oormthonUNIV-Team-7/Backend, pull requests merged in 2024-09, with the labels that each got.

#11 [feat] balanceGame API 구현
  src/main/java/goormthonUniv/floating/controller/BalanceGameController.java
  src/main/java/goormthonUniv/floating/domain/BalanceGame.java
  src/main/java/goormthonUniv/floating/domain/Member.java
  src/main/java/goormthonUniv/floating/repository/BalanceGameRepository.java
  src/main/java/goormthonUniv/floating/response/BalanceGameResponse.java
  src/main/java/goormthonUniv/floating/service/BalanceGameService.java
Labels: 🚀 Feat

#14 [fix] BalanceGame JSON response format 수정
  src/main/java/goormthonUniv/floating/controller/BalanceGameController.java
  src/main/resources/application.properties
Labels: 🏷 Fix

#17 [chore] docker 배포 환경 세팅
  docker-compose.prod.yml
Labels: 🧭 Chore

#21 [feat] CORS 에러 해결
  src/main/java/goormthonUniv/floating/config/WebConfig.java
Labels: 🚀 Feat

#22 [feat] CSV 데이터 파일 생성
  src/main/resources/csv/BalanceGame.csv
  src/main/resources/csv/MiniGame.csv
  src/main/resources/csv/TalkSubject.csv
Labels: 🚀 Feat

#26 fix: CSV 데이터 오류 수정
  src/main/resources/csv/MiniGame.csv
  src/main/resources/csv/TalkSubject.csv
Labels: 🏷 Fix

#29 [feat] Board API 구현
  src/main/java/goormthonUniv/floating/controller/BoardController.java
  src/main/java/goormthonUniv/floating/domain/Board.java
  src/main/java/goormthonUniv/floating/repository/BoardRepository.java
  src/main/java/goormthonUniv/floating/response/BoardResponse.java
  src/main/java/goormthonUniv/floating/service/BoardService.java
  src/main/resources/csv/BalanceGame.csv
  src/main/resources/csv/MiniGame.csv
  src/main/resources/csv/TalkSubject.csv
Labels: 🚀 Feat

#30 [feat] 구글 소셜 로그인 구현
  build.gradle
  src/main/java/goormthonUniv/floating/FloatingApplication.java
  src/main/java/goormthonUniv/floating/config/SecurityConfig.java
  src/main/java/goormthonUniv/floating/config/WebConfig.java
  src/main/java/goormthonUniv/floating/controller/LoginController.java
  src/main/java/goormthonUniv/floating/domain/Favorite.java
  src/main/java/goormthonUniv/floating/domain/FavoriteCategory.java
  src/main/java/goormthonUniv/floating/domain/Role.java
  src/main/java/goormthonUniv/floating/domain/User.java
  src/main/java/goormthonUniv/floating/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/goormthonUniv/floating/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/goormthonUniv/floating/repository/UserRepository.java
  src/main/java/goormthonUniv/floating/response/OAuthAttributes.java
  src/main/java/goormthonUniv/floating/service/CustomOAuth2UserService.java
  src/main/java/goormthonUniv/floating/util/AuthenticationFilter.java
  src/main/java/goormthonUniv/floating/util/JwtTokenUtil.java
  src/main/resources/application.yml
Labels: 🚀 Feat

#33 feat: User API 구현
  src/main/java/goormthonUniv/floating/controller/UserController.java
  src/main/java/goormthonUniv/floating/response/UserResponse.java
  src/main/java/goormthonUniv/floating/service/UserService.java
Labels: 🚀 Feat
